/**
 * set-env.js
 * Genera src/environments/environment.ts y environment.prod.ts a partir de variables de entorno.
 *
 * Fuentes (en orden de prioridad):
 *   1. process.env (Vercel CI / shell exportado)
 *   2. .env.local  (creado por `vercel env pull .env.local`)
 *   3. .env
 *
 * Las variables ya presentes en process.env NO se sobrescriben.
 */
const fs = require('fs');
const path = require('path');

function loadDotEnv(file) {
  const fullPath = path.join(__dirname, file);
  if (!fs.existsSync(fullPath)) return false;

  const content = fs.readFileSync(fullPath, 'utf-8');
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = value;
    }
  }
  console.log(`✔ Loaded env from ${file}`);
  return true;
}

// .env.local tiene prioridad sobre .env (convención de Vercel/Next/dotenv)
loadDotEnv('.env.local') || loadDotEnv('.env');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
const DEEPSEEK_MODEL = process.env.DEEPSEEK_MODEL || 'deepseek-v4-flash';

function buildEnvFile(production) {
  return `// Auto-generated by set-env.js — do not edit manually.
export const environment = {
  production: ${production},
  supabaseUrl: '${SUPABASE_URL}',
  supabaseAnonKey: '${SUPABASE_ANON_KEY}',
  aiModel: '${DEEPSEEK_MODEL}',
  aiEndpoint: '/api/generate-phrases'
};
`;
}

const dir = path.join(__dirname, 'src', 'environments');
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync(path.join(dir, 'environment.ts'), buildEnvFile(false));
fs.writeFileSync(path.join(dir, 'environment.prod.ts'), buildEnvFile(true));

const mask = (v) => (v ? `***SET*** (${v.length} chars)` : '(empty)');
console.log('✔ Environment files generated:');
console.log(`  • SUPABASE_URL       → ${mask(SUPABASE_URL)}`);
console.log(`  • SUPABASE_ANON_KEY  → ${mask(SUPABASE_ANON_KEY)}`);
console.log(`  • DEEPSEEK_MODEL     → ${DEEPSEEK_MODEL}`);

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('⚠  Supabase env vars empty. Run `npm run vercel:pull` to fetch them from Vercel.');
}
