// Auto-generated by set-env.js — do not edit manually.
export const environment = {
  production: true,
  supabaseUrl: '',
  supabaseAnonKey: '',
  aiModel: 'deepseek-v4-flash',
  aiEndpoint: '/api/generate-phrases'
};
